'\" t
.\"     Title: sslmate
.\"    Author: SSLMate <sslmate@sslmate.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2018-06-20
.\"    Manual: SSLMate
.\"    Source: SSLMate 1.7.0
.\"  Language: English
.\"
.TH "SSLMATE" "1" "2018\-06\-20" "SSLMate 1.7.0" "SSLMate"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sslmate \- buy and manage SSL certificates
.SH "SYNOPSIS"
.HP \w'\fBsslmate\ \fR\fB[\fIOPTIONS\fR]\fR\fB\ \fR\fB\fICOMMAND\fR\fR\fB\ \fR\fB[\fIARGS\fR...]\fR\ 'u
\fBsslmate \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fICOMMAND\fR\fR\fB \fR\fB[\fIARGS\fR...]\fR
.SH "COMMON COMMANDS"
.HP \w'\fBsslmate\ buy\ \fR\fB\fIHOSTNAME\fR...\fR\ 'u
\fBsslmate buy \fR\fB\fIHOSTNAME\fR...\fR
.HP \w'\fBsslmate\ renew\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate renew \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ reissue\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate reissue \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ rekey\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate rekey \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ revoke\ \fR\fB[\-\-all]\fR\fB\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate revoke \fR\fB[\-\-all]\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ download\ \fR\fB\fIHOSTNAME\fR...\fR\ 'u
\fBsslmate download \fR\fB\fIHOSTNAME\fR...\fR
.HP \w'\fBsslmate\ download\ \fR\fB\-\-all\fR\ 'u
\fBsslmate download \fR\fB\-\-all\fR
.HP \w'\fBsslmate\ list\fR\ 'u
\fBsslmate list\fR
.HP \w'\fBsslmate\ show\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate show \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ edit\ \fR\fB\fIOPTIONS\fR...\fR\fB\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate edit \fR\fB\fIOPTIONS\fR...\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ test\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate test \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ mkconfig\ \fR\fB\fITEMPLATE\fR\fR\fB\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate mkconfig \fR\fB\fITEMPLATE\fR\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ import\ \fR\fB\fIKEYFILE\fR\fR\fB\ \fR\fB\fICERTFILE\fR\fR\ 'u
\fBsslmate import \fR\fB\fIKEYFILE\fR\fR\fB \fR\fB\fICERTFILE\fR\fR
.HP \w'\fBsslmate\ retry\-approval\ \fR\fB\fIHOSTNAME\fR\fR\ 'u
\fBsslmate retry\-approval \fR\fB\fIHOSTNAME\fR\fR
.HP \w'\fBsslmate\ link\fR\ 'u
\fBsslmate link\fR
.SH "DESCRIPTION"
.PP
\fBsslmate\fR
is the command line client for SSLMate (\m[blue]\fBhttps://sslmate\&.com\fR\m[]), a service for purchasing and managing SSL certificates\&. SSLMate provides easy\-to\-use tools for buying, renewing, and revoking certificates, for monitoring the expiration date of your certificates, and for synchronizing your certificates between your servers\&.
.PP
SSLMate emphasizes speed, ease\-of\-use, and automation\&. For example, the command to purchase a certificate (\fBsslmate buy\fR) typically completes in under a minute and automates the steps of generating a private key, generating a CSR, and building a certificate bundle\&. SSLMate can automatically renew your certificates, and you can run
\fBsslmate download\fR
from a cron job so that renewed certificates are automatically downloaded to your server\&.
.PP
To use the
\fBsslmate\fR
command, you must create a free account at
\m[blue]\fBhttps://sslmate\&.com\fR\m[]\&.
.SH "COMMANDS"
.PP
\fBsslmate\fR
is logically divided into several sub\-commands which perform distinct tasks\&. Each sub\-command, and its arguments, are documented below\&. Note that arguments and options to sub\-commands must be specified on the command line
\fIafter\fR
the name of the sub\-command\&.
.PP
\fBbuy \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIHOSTNAME\fR...\fR
.RS 4
Generate a private key and purchase a certificate for the given hostname(s)\&.
.sp
If only one hostname is specified, a standard single\-hostname certificate is issued\&. The hostname is placed in the certificate\*(Aqs common name (CN) field as well as a subjectAltName field\&. Unless the hostname already starts with "www\&.", a subjectAltName is added, free of charge, for the hostname prefixed with "www\&." (e\&.g\&. if the hostname is "example\&.com", a subjectAltName is added for "www\&.example\&.com")\&.
.sp
If the hostname starts with "*\&.", then a wildcard certificate is issued which is valid for the wildcard domain itself and all hostnames directly below the wildcard domain\&. The certificate is not valid for hostnames two or more levels below the wildcard domain\&. For example, "*\&.example\&.com" matches "example\&.com", "www\&.example\&.com", and "subdomain\&.example\&.com", but not "www\&.subdomain\&.example\&.com")\&.
.sp
If more than one hostname is specified, a multi\-hostname certificate is issued\&. The first hostname is the primary name of the certificate and is placed in the certificate\*(Aqs common name field, as well as a subjectAltName field\&. The remaining hostnames are placed in subjectAltNames\&. The certificate is referred to by its primary name when downloading, renewing, reissuing, etc\&. The primary name cannot be changed without purchasing a new certificate, but alternative names can be added and removed after the certificate is issued by running
\fBsslmate edit\fR\&.
.sp
The following options are understood:
.PP
\fB\-\-auto\-renew\fR, \fB\-\-no\-auto\-renew\fR
.RS 4
Enable or disable automatic renewal for this certificate\&. If neither option is specified, your account\*(Aqs default auto\-renewal setting is used\&.
.sp
The auto\-renewal setting of an already\-purchased certificate can be changed from the SSLMate website\&.
.RE
.PP
\fB\-\-approval=email|dns|http\fR
.RS 4
Use the given method to prove ownership of your domain\&.
.sp
When "email" is used (the default), you must respond to an email sent to one of the administrative addresses for your domain\&. You will be prompted for the email address when running
\fBsslmate buy\fR, or you can specify it on the command line with the
\fB\-\-email=\fR\fB\fIADDRESS\fR\fR
option\&.
.sp
When "dns" is used, you must add a specific DNS record under your domain\&. If you have configured your SSLMate account to integrate with a supported DNS provider (see
\m[blue]\fBhttps://sslmate\&.com/account/integrations\fR\m[]), then the DNS record will be added automatically\&. Otherwise, the DNS record will be displayed and you will need to add it manually\&.
.sp
When "http" is used, you must configure the web server for your domain to proxy certain URLs to an SSLMate approval server, as described at
\m[blue]\fBhttps://sslmate\&.com/help/approval/http\fR\m[]\&. Once your web server is configured, certificates using HTTP approval will be approved and issued automatically\&.
.sp
When purchasing a multi\-hostname certificate, each hostname must be approved separately\&. The approval method specified by this option applies to every hostname\&. To use a different method for a hostname, specify an option of the form
\fB\-\-approval=\fR\fB\fIHOSTNAME\fR\fR\fB=\fR\fB\fIMETHOD\fR\fR\&.
.RE
.PP
\fB\-\-email=\fR\fB\fIADDRESS\fR\fR
.RS 4
Send the approval email to the given email address\&. This address must be one of the addresses that is listed when you run
\fBsslmate buy\fR
interactively\&. Only applicable if email approval is used\&.
.sp
When purchasing a multi\-hostname certificate, this email address is used for every hostname\&. To use a different email address for a hostname, specify an option of the form
\fB\-\-email=\fR\fB\fIHOSTNAME\fR\fR\fB=\fR\fB\fIADDRESS\fR\fR\&.
.RE
.PP
\fB\-\-timeout=\fR\fB\fISECONDS\fR\fR
.RS 4
Wait up to
\fISECONDS\fR
seconds for the certificate to be issued\&. If the certificate is not issued before the timeout elapses,
\fBsslmate\fR
exits without downloading any certificate files\&. Instead, the certificate must be downloaded later with the
\fBsslmate download\fR
command\&.
.RE
.PP
\fB\-\-no\-wait\fR
.RS 4
Return immediately after placing the order instead of waiting for the certificate to be issued\&. If this option is used, no certificate files are downloaded; instead the certificate must be downloaded separately with the
\fBsslmate download\fR
command\&.
.sp
This option is equivalent to
\fB\-\-timeout 0\fR\&.
.RE
.PP
\fB\-\-temp\fR
.RS 4
Instead of waiting for the certificate to be issued, install a temporary, self\-signed, certificate and return immediately\&. The temporary certificate will not be trusted by clients, but it can be used to configure your server software while waiting for the real certificate to be issued\&.
.sp
When the real certificate is issued, it can be downloaded with the
\fBsslmate download\fR
command\&.
.RE
.PP
\fB\-\-ev\fR
.RS 4
Purchase an extended validation (EV) certificate, instead of a domain validation (DV) certificate\&.
.sp
EV certificates provide equivalent security to DV certificates, but are subject to a more rigorous approval process\&. An EV certificate verifies not only that the bearer of the certificate controls the domain in question, but also that the domain is owned by a legally established business or organization with a verifiable identity\&. When viewing a website with an EV certificate, web browsers display a green address bar along with the verified name of the organization\&.
.sp
To purchase EV certificates, you must first provide additional information about your organization on your
\m[blue]\fBonline SSLMate account page\fR\m[]\&\s-2\u[1]\d\s+2\&. Unlike a DV certificate, an EV certificate takes several days to issue while your identity is verified\&. When purchasing an EV certificate,
\fBsslmate buy\fR
returns immediately with a temporary self\-signed certificate (as if the
\fB\-\-temp\fR
had been specified)\&. When your real certificate is issued, you will receive an email and be able to download it with the
\fBsslmate download\fR
command\&.
.sp
If you\*(Aqre not sure what kind of certificate you need, buy a DV certificate (the default)\&.
.RE
.PP
\fB\-\-coupon=\fR\fB\fICODE\fR\fR
.RS 4
Use the given coupon code for a discount\&.
.RE
.PP
\fB\-\-invoice\-note=\fR\fB\fINOTE\fR\fR
.RS 4
Include the given note with the invoice for this purchase\&.
.RE
.PP
\fB\-\-email\-invoice\-to=\fR\fB\fIADDRESS\fR\fR
.RS 4
Email the invoice for this purchase to the given address\&.
.sp
By default, invoices are not emailed, but can be downloaded from your
\m[blue]\fBonline SSLMate dashboard\fR\m[]\&\s-2\u[2]\d\s+2\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Buy the certificate even if there are existing key and certificate files, or if an active certificate with this name already exists in your SSLMate account\&. Existing key and certificate files will be overwritten\&.
.RE
.PP
\fB\-\-key\-type=rsa|ecdsa\fR
.RS 4
Specify the type of key to generate: RSA (the default), or ECDSA (elliptic curve)\&. The certificate will be signed with a signature of the same type\&.
.sp
RSA provides the best compatibility with clients\&. ECDSA provides better performance during the TLS handshake, but is not supported by older web browsers (such as IE 8 on Windows XP, Android 2\&.3, and Java 6)\&. If in doubt, use RSA\&.
.sp
The default key type can be changed by setting the
\fBkey_type\fR
configuration option (see the CONFIGURATION section for details)\&.
.RE
.PP
\fB\-\-multi\fR
.RS 4
Buy a multi\-hostname certificate even if only one hostname was specified on the command line\&. This option is only necessary if you want to buy a multi\-hostname certificate with only one hostname\&.
.RE
.RE
.PP
\fBrenew \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Renew the certificate for the given hostname\&.
.sp
The following options are understood:
.PP
\fB\-\-timeout=\fR\fB\fISECONDS\fR\fR
.RS 4
Wait up to
\fISECONDS\fR
seconds for the certificate to be issued\&. If the certificate is not issued before the timeout elapses,
\fBsslmate\fR
exits without downloading any certificate files\&. Instead, the certificate must be downloaded later with the
\fBsslmate download\fR
command\&.
.RE
.PP
\fB\-\-no\-wait\fR
.RS 4
Return immediately after placing the order instead of waiting for the new certificate to be issued\&. If this option is used, no certificate files are downloaded; instead the new certificate must be downloaded separately with the
\fBsslmate download\fR
command\&.
.sp
This option is equivalent to
\fB\-\-timeout 0\fR\&.
.RE
.PP
\fB\-\-coupon=\fR\fB\fICODE\fR\fR
.RS 4
Use the given coupon code for a discount\&.
.RE
.PP
\fB\-\-invoice\-note=\fR\fB\fINOTE\fR\fR
.RS 4
Include the given note with the invoice for this purchase\&.
.RE
.PP
\fB\-\-email\-invoice\-to=\fR\fB\fIADDRESS\fR\fR
.RS 4
Email the invoice for this purchase to the given address\&.
.sp
By default, invoices are not emailed, but can be downloaded from your
\m[blue]\fBonline SSLMate dashboard\fR\m[]\&\s-2\u[2]\d\s+2\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Renew the certificate even if it\*(Aqs not about to expire\&. Note that the renewed certificate will expire one year from the today\*(Aqs date, not from the expiration date of the current certificate\&.
.RE
.RE
.PP
\fBreissue \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Generate a new private key (unless
\fB\-\-same\-key\fR
is specified) and reissue the certificate for the given hostname\&.
.sp
Note:
\fBsslmate reissue\fR
without the
\fB\-\-same\-key\fR
option is deprecated\&. Starting with SSLMate 2\&.0,
\fB\-\-same\-key\fR
will be implied\&. To reissue a certificate with a new key, use
\fBsslmate rekey\fR
instead\&.
.sp
Reissuing a certificate does
\fInot\fR
revoke it\&. Use the
\fBsslmate revoke\fR
command to revoke a certificate after you have reissued it\&.
.sp
The following options are understood:
.PP
\fB\-\-same\-key\fR
.RS 4
Keep the same private key when reissuing\&. This is useful if you are reissuing a certificate not because of a lost key, but to add or remove the alternative names of a multi\-hostname certificate\&.
.sp
Note: Starting with SSLMate 2\&.0,
\fB\-\-same\-key\fR
will be implied\&. To reissue a certificate with a new key, use
\fBsslmate rekey\fR
instead\&.
.RE
.PP
\fB\-\-timeout=\fR\fB\fISECONDS\fR\fR
.RS 4
Wait up to
\fISECONDS\fR
seconds for the certificate to be issued\&. If the certificate is not issued before the timeout elapses,
\fBsslmate\fR
exits without downloading any certificate files\&. Instead, the certificate must be downloaded later with the
\fBsslmate download\fR
command\&.
.RE
.PP
\fB\-\-no\-wait\fR
.RS 4
Return immediately after requesting the reissue instead of waiting for the new certificate to be issued\&. If this option is used, no certificate files are downloaded; instead the new certificate must be downloaded separately with the
\fBsslmate download\fR
command\&.
.sp
This option is equivalent to
\fB\-\-timeout 0\fR\&.
.RE
.RE
.PP
\fBrekey \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Generate a new private key and reissue the certificate for the given hostname\&.
.sp
Reissuing a certificate does
\fInot\fR
revoke it\&. Use the
\fBsslmate revoke\fR
command to revoke a certificate after you have rekeyed it\&.
.sp
The following options are understood:
.PP
\fB\-\-timeout=\fR\fB\fISECONDS\fR\fR
.RS 4
Wait up to
\fISECONDS\fR
seconds for the certificate to be issued\&. If the certificate is not issued before the timeout elapses,
\fBsslmate\fR
exits without downloading any certificate files\&. Instead, the certificate must be downloaded later with the
\fBsslmate download\fR
command\&.
.RE
.PP
\fB\-\-no\-wait\fR
.RS 4
Return immediately after requesting the rekey instead of waiting for the new certificate to be issued\&. If this option is used, no certificate files are downloaded; instead the new certificate must be downloaded separately with the
\fBsslmate download\fR
command\&.
.sp
This option is equivalent to
\fB\-\-timeout 0\fR\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Overwrite existing files\&.
.RE
.PP
\fB\-\-key\-type=rsa|ecdsa\fR
.RS 4
Specify the type of the new key: RSA (the default), or ECDSA (elliptic curve)\&. The certificate will be signed with a signature of the same type\&.
.sp
See the documentation for
\fBsslmate buy\fR
for more information\&. If in doubt, do not use this option\&.
.RE
.RE
.PP
\fBrevoke \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Revoke the certificate(s) for the given hostname\&.
.sp
Revoking a certificate does
\fInot\fR
issue a new certificate\&. If you need a new certificate, use the
\fBsslmate reissue\fR
command to generate and issue a new certificate
\fIbefore\fR
running
\fBsslmate revoke\fR\&.
.sp
The following options are understood:
.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
Revoke
\fIall\fR
certificates for this hostname, including the most recent active certificate\&. If this option is omitted, all but the most recent active certificate are revoked\&.
.sp
WARNING: if you use this option, SSLMate will no longer be able to issue new certificates for this hostname unless you buy a brand new certificate\&. Generally, to revoke a certificate, you should first reissue it with the
\fBreissue\fR
command and then use
\fBrevoke\fR\fIwithout\fR
the
\fB\-\-all\fR
option\&. Only use
\fB\-\-all\fR
if you no longer need any certificates for a hostname\&.
.sp
You will be prompted for confirmation unless you also specify the
\fB\-\-batch\fR
global option\&.
.RE
.RE
.PP
\fBdownload \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIHOSTNAME\fR...\fR
.RS 4
Download the certificate(s) for the given hostname(s), or, if
\fB\-\-all\fR
is specified, for all hostnames that have keys in the
\fIkey_directory\fR\&.
.sp
Certificate files are downloaded from your SSLMate account to your configured
\fIcert_directory\fR
(/etc/sslmate
by default if run as root,
$PWD
if run as non\-root)\&. Existing certificate files are replaced\&. Exits with status code 0 if new certificate files were downloaded, or 10 if the most up\-to\-date certificate files have already been downloaded\&.
.sp
This command is designed to be run from a cron job or configuration management script so that auto\-renewed certificates are automatically propagated to your server\&. You can check the exit status and, if zero, restart daemons so they load the latest version of the certificate\&.
.sp
The following options are understood:
.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
Download certificate files for every key present in the
\fIkey_directory\fR
(/etc/sslmate
by default if run as root,
$PWD
if run as non\-root)\&.
.sp
If this option is used, specific hostnames cannot be specified on the command line\&.
.RE
.PP
\fB\-\-temp\fR
.RS 4
If the certificate has not been issued yet, download a temporary, self\-signed, certificate instead\&. See the documentation for
\fBsslmate buy\fR
for more information about temporary certificates\&.
.RE
.RE
.PP
\fBlist \fR\fB[\fIOPTIONS\fR]\fR
.RS 4
List the certificates in your SSLMate account\&.
.sp
The following options are understood:
.PP
\fB\-\-local\fR
.RS 4
List only certificates that are also installed locally\&.
.RE
.PP
\fB\-\-no\-local\fR
.RS 4
List only certificates that are
\fInot\fR
installed locally\&.
.RE
.PP
\fB\-c \fR\fB\fICOLUMNS\fR\fR, \fB\-\-columns=\fR\fB\fICOLUMNS\fR\fR
.RS 4
Include the given columns in the output, where
\fICOLUMNS\fR
is a comma\-separated list of the following column names:
.PP
name
.RS 4
The certificate\*(Aqs common name\&.
.RE
.PP
status
.RS 4
The certificate\*(Aqs status\&.
.RE
.PP
expiration
.RS 4
The certificate\*(Aqs expiration date, in YYYY\-MM\-DD format\&.
.RE
.PP
local_status
.RS 4
The status of the locally\-installed copy of the certificate ("Installed", "Temporary", "Mismatched key", "No key file", "Out\-of\-date", or "None")\&.
.RE
.PP
fingerprint
.RS 4
The certificate\*(Aqs SHA\-1 fingerprint, in uppercase hex with octets separated by colons\&.
.RE
.PP
sha256_fingerprint
.RS 4
The certificate\*(Aqs SHA\-256 fingerprint, in uppercase hex with octets separated by colons\&.
.RE
.PP
auto_renew
.RS 4
The certificate\*(Aqs auto\-renew setting\&.
.RE
.PP
type
.RS 4
The certificate\*(Aqs type ("DV" or "EV")\&.
.RE
.PP
approval_method
.RS 4
The approval method\&.
.RE
.PP
approver_email
.RS 4
The approver email address\&.
.RE
.RE
.PP
\fB\-\-sort=\fR\fB\fICOLUMNS\fR\fR
.RS 4
Sort the output by the given column(s), where
\fICOLUMNS\fR
is a comma\-separated list of column names as understood by the
\fB\-\-columns\fR
option\&. If more than one column is specified, the latter columns are used to break ties if the earlier columns are equal\&.
.sp
Columns are sorted in ascending order by default\&. To sort a column in descending order, prefix it with a ^ symbol\&.
.RE
.PP
\fB\-z\fR
.RS 4
Generate machine\-parseable output\&. By default, columns and lines are separated by a NUL character, but this can be customized by setting the
\fIOFS\fR
(output field separator) and
\fIORS\fR
(output record separator) environment variables\&.
.sp
When using
\fB\-z\fR, you must explicitly enumerate the columns you want with the
\fB\-\-columns\fR
option\&.
.sp
The output of
\fB\-z\fR
is guaranteed not to change format, making it suitable for use in scripts\&.
.RE
.RE
.PP
\fBshow \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Show information about the given certificate\&.
.sp
The following options are understood:
.PP
\fB\-f \fR\fB\fIFIELDS\fR\fR, \fB\-\-fields=\fR\fB\fIFIELDS\fR\fR
.RS 4
Include the given fields in the output, where
\fIFIELDS\fR
is a comma\-separated list of the following column names:
.PP
name
.RS 4
The certificate\*(Aqs common name\&.
.RE
.PP
alt_names
.RS 4
The certificate\*(Aqs subject alternative names (for multi\-hostname certs only)\&.
.RE
.PP
status
.RS 4
The certificate\*(Aqs status\&.
.RE
.PP
expiration
.RS 4
The certificate\*(Aqs expiration date, in YYYY\-MM\-DD format\&.
.RE
.PP
local_status
.RS 4
The status of the locally\-installed copy of the certificate ("Installed", "Temporary", "Mismatched key", "No key file", "Out\-of\-date", or "None")\&.
.RE
.PP
fingerprint
.RS 4
The certificate\*(Aqs SHA\-1 fingerprint, in uppercase hex with octets separated by colons\&.
.RE
.PP
sha256_fingerprint
.RS 4
The certificate\*(Aqs SHA\-256 fingerprint, in uppercase hex with octets separated by colons\&.
.RE
.PP
auto_renew
.RS 4
The certificate\*(Aqs auto\-renew setting\&.
.RE
.PP
type
.RS 4
The certificate\*(Aqs type ("DV" or "EV")\&.
.RE
.PP
approval_method
.RS 4
The approval method\&.
.RE
.PP
approver_email
.RS 4
The approver email address\&.
.RE
.RE
.PP
\fB\-\-json\fR
.RS 4
Generate JSON output\&. The output format is guaranteed not to change, apart from backwards\-compatible changes such as adding new fields to the JSON object\&.
.RE
.RE
.PP
\fBedit \fR\fB\fIOPTIONS\fR...\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Change one or more setting of the given certificate\&. The settings are specified by the
\fIOPTIONS\fR
arguments, as described below\&. Every setting is optional; if omitted, the setting is left unchanged\&.
.PP
\fB\-\-approval=email|dns|http\fR
.RS 4
Change the approval method for this certificate\&. The new method will be used for approving future reissues and renewals of the certificate\&. If the certificate is currently pending approval, the approval process will be re\-initiated\&.
.sp
For more information about approval methods, see the documentation for
\fBsslmate buy\fR\&.
.sp
If this is a multi\-hostname certificate, the approval method specified by this option applies to every hostname\&. To edit the approval method for a single hostname only, pass an option of the form
\fB\-\-approval=\fR\fB\fIHOSTNAME\fR\fR\fB=\fR\fB\fIMETHOD\fR\fR\&.
.RE
.PP
\fB\-\-email=\fR\fB\fIADDRESS\fR\fR
.RS 4
Change the approver email address of this certificate\&. The new address will be used for approving future reissues and renewals of the certificate\&. If the certificate is currently pending approval, the approval email will be resent to the new address\&.
.sp
The new address must be one of the acceptable addresses that is listed when you run
\fBsslmate buy\fR
for this host name\&. This option is only applicable when email approval is used\&.
.sp
If this is a multi\-hostname certificate, the email address specified by this option applies to every hostname\&. To edit the email address for a single hostname only, pass an option of the form
\fB\-\-email=\fR\fB\fIHOSTNAME\fR\fR\fB=\fR\fB\fIMETHOD\fR\fR\&.
.RE
.PP
\fB\-\-auto\-renew\fR, \fB\-\-no\-auto\-renew\fR
.RS 4
Enable or disable auto\-renew for this certificate\&.
.RE
.PP
\fB\-\-add\-name=\fR\fB\fIHOSTNAME\fR\fR, \fB\-\-rm\-name=\fR\fB\fIHOSTNAME\fR\fR
.RS 4
Add or remove the given hostname to or from this certificate\&. This certificate must be a multi\-hostname certificate, and only alternative names (not the common name) can be removed\&.
.sp
The name is not added or removed immediately\&. Instead, the changes take effect on the next call to
\fBsslmate reissue\fR\&. Any names that were added since the last issuance will need to be approved\&. Existing names do not need to be re\-approved as long as you preserve the existing private key by passing the
\fB\-\-same\-key\fR
option to
\fBsslmate reissue\fR\&. If there has been a net increase in hostnames since the last issuance, your account will be charged for the new names\&.
.sp
Note that removing all alternative hostnames does not convert the certificate to a single\-hostname certificate\&. For that, you must use the
\fB\-\-no\-multi\fR
option\&.
.RE
.PP
\fB\-\-multi\fR, \fB\-\-no\-multi\fR
.RS 4
Change the scope of this certificate (single\-hostname or multi\-hostname)\&. See the
\fBsslmate buy\fR
documentation for a discussion of the differences\&.
.sp
Changes to the certificate scope take effect only when renewing\&. To "upgrade" an existing single\-hostname certificate to a multi\-hostname certificate, first edit its scope and add alternative names with
\fBsslmate edit\fR
and then force an early renewal with
\fBsslmate renew \-\-force\fR\&.
.RE
.PP
\fB\-\-type=dv|ev\fR
.RS 4
Change the type of this certificate (domain validation or extended validation)\&. See the
\fBsslmate buy\fR
documentation for a discussion of certificate types\&.
.sp
Changes to the certificate type take effect only when renewing\&. To "upgrade" an existing DV certificate to EV, first change its type with
\fBsslmate edit\fR
and then force an early renewal with
\fBsslmate renew \-\-force\fR\&.
.RE
.RE
.PP
\fBimport \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIKEYFILE\fR\fR\fB \fR\fB\fICERTFILE\fR\fR
.RS 4
Import the given certificate to your SSLMate account\&. An imported certificate works just like a certificate purchased from SSLMate with
\fBsslmate buy\fR, meaning SSLMate will monitor its expiration and you can set up automated renewals for it\&.
.sp
You must specify the paths to the key file (\fIKEYFILE\fR) and to the certificate file (\fICERTFILE\fR)\&. Note that the private key is
\fInot\fR
uploaded to SSLMate;
\fBsslmate\fR
only uses it to generate a certificate signing request\&.
.sp
The following options are understood:
.PP
\fB\-\-auto\-renew\fR, \fB\-\-no\-auto\-renew\fR
.RS 4
Enable or disable automatic renewal for this certificate\&. If neither option is specified, your account\*(Aqs default auto\-renewal setting is used\&.
.RE
.PP
\fB\-\-no\-install\fR
.RS 4
Don\*(Aqt install the key and certificate files to the local key and certificate directories\&. (By default, keys and certificates are copied there, as if the certificate had just been purchased with the
\fBsslmate buy\fR
command\&.)
.RE
.PP
\fB\-\-approval=email|dns|http\fR
.RS 4
When renewing, use the given method to prove ownership of your domain\&.
.sp
For more information about approval methods, see the documentation for
\fBsslmate buy\fR\&.
.sp
If this is a multi\-hostname certificate, the approval method specified by this option applies to every hostname\&. To specify a different approval method for a particular hostname, pass an option of the form
\fB\-\-approval=\fR\fB\fIHOSTNAME\fR\fR\fB=\fR\fB\fIMETHOD\fR\fR\&.
.RE
.PP
\fB\-\-email=\fR\fB\fIADDRESS\fR\fR
.RS 4
When renewing, send the domain ownership email to the given email address instead of prompting for one\&. This address must be one of the addresses that is listed when you run
\fBsslmate import\fR
interactively\&. This option is only applicable when email approval is used\&.
.sp
If this is a multi\-hostname certificate, the email address specified by this option applies to every hostname\&. To specify a different email address for a particular hostname, pass an option of the form
\fB\-\-approval=\fR\fB\fIHOSTNAME\fR\fR\fB=\fR\fB\fIMETHOD\fR\fR\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Import the certificate even if there are existing key and certificate files, or if an active certificate with this name already exists in your SSLMate account\&. Existing key and certificate files will be overwritten\&.
.RE
.RE
.PP
\fBtest \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Test whether your certificate for
\fIHOSTNAME\fR
has been correctly installed\&.
.sp
This command works by connecting to the host specified in the certificate and checking that the server returns both the correct certificate and the correct certificate chain\&. The results of the test are printed to standard out\&. There may be more than one test result if
\fIHOSTNAME\fR
resolves to more than one IP address\&. This command exits with status 0 if all tests were successful, 11 if one or more tests failed, and some other exit code if there was an error that prevented the test from running\&.
.sp
The following options are understood:
.PP
\fB\-p \fR\fB\fIPORTNUMBER\fR\fR, \fB\-\-port=\fR\fB\fIPORTNUMBER\fR\fR
.RS 4
Test the server on the given port number\&. (Default: 443)
.RE
.PP
\fB\-h \fR\fB\fIHOSTNAME\fR\fR, \fB\-\-host=\fR\fB\fIHOSTNAME\fR\fR
.RS 4
Test the server running on the given hostname\&. Defaults to the certificate\*(Aqs common name\&.
.RE
.RE
.PP
\fBmkconfig \fR\fB[\fIOPTIONS\fR]\fR\fB \fR\fB\fITEMPLATE\fR\fR\fB \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Output the configuration directives necessary to securely use the given certificate with the server software (such as Apache, nginx, etc\&.) specified by the
\fITEMPLATE\fR
argument\&. For a list of server software for which configuration templates are available, pass the
\fB\-\-templates\fR
option\&.
.sp
By default,
\fBsslmate mkconfig\fR
includes the "intermediate compatibility" security settings recommended by
\m[blue]\fBMozilla\*(Aqs Server Side TLS Guide\fR\m[]\&\s-2\u[3]\d\s+2\&. These settings enable forward secrecy and disable broken ciphers and protocols, while supporting a broad range of clients\&.
.sp
The following options are understood:
.PP
\fB\-\-templates\fR
.RS 4
Output a list of available configuration templates\&. No other arguments are required if you use this option\&.
.RE
.PP
\fB\-\-no\-security\fR
.RS 4
Don\*(Aqt include recommended security settings\&. Output only the bare minimum configuration needed to use the certificate\&.
.RE
.RE
.PP
\fBretry\-approval \fR\fB\fIHOSTNAME\fR\fR
.RS 4
Retry the approval process of a certificate that\*(Aqs pending approval\&. If the certificate uses email approval, the email will be resent\&. If the certificate uses DNS approval, the DNS record will be added if not already present, and then re\-checked\&.
.sp
To change the approval method or approver email of a pending certificate, use the
\fBsslmate edit\fR
command\&.
.RE
.PP
\fBlink\fR
.RS 4
Link this system with your SSLMate account\&.
\fBsslmate link\fR
prompts for your SSLMate username and password and writes your API credentials to your personal SSLMate configuration file, permitting you to use the
\fBsslmate\fR
commands without having to enter your username and password\&.
.sp
Note: if you have enabled a daily purchase limit through your
\m[blue]\fBonline SSLMate account page\fR\m[]\&\s-2\u[1]\d\s+2, you will always need to enter your password after exceeding the limit, even if you have linked this system\&.
.RE
.PP
\fBhelp \fR\fB[\fICOMMAND\fR]\fR
.RS 4
Display help for the given
\fICOMMAND\fR, or an overview of all commands if no command is specified\&.
.RE
.PP
\fBversion \fR\fB[\fIOPTIONS\fR]\fR
.RS 4
Print the currently\-installed version of
\fBsslmate\fR\&. By default, check if this version is up\-to\-date and print a message if a newer version is available\&.
.sp
The following options are understood:
.PP
\fB\-\-no\-check\fR
.RS 4
Do not check for a newer version\&.
.RE
.PP
\fB\-\-is\-latest\fR
.RS 4
Print no output, but exit with 0 if this version of
\fBsslmate\fR
is up\-to\-date, 10 if a newer version is available, and some other exit code if there is an error\&.
.sp
This option cannot be combined with
\fB\-\-no\-check\fR\&.
.RE
.RE
.SH "GLOBAL OPTIONS"
.PP
The following options are understood by
\fBsslmate\fR
and can be used with any sub\-command\&. Since they apply globally to
\fBsslmate\fR, they must be specified on the command line
\fIbefore\fR
the sub\-command name\&.
.PP
\fB\-\-batch\fR
.RS 4
Don\*(Aqt prompt for confirmation or for additional information\&. This option should be used when running
\fBsslmate\fR
unattended from scripts\&.
.sp
Any information which
\fBsslmate\fR
would have prompted for must be specified on the command line instead\&. For example, when buying a certificate, you must specify the approval method with the
\fB\-\-approval\fR
option, and, if applicable, the approver email address with the
\fB\-\-email=\fR\fB\fIADDRESS\fR\fR
option\&.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
Display additional information about what
\fBsslmate\fR
is doing\&.
.RE
.PP
\fB\-p \fR\fB\fIPROFILE\fR\fR, \fB\-\-profile=\fR\fB\fIPROFILE\fR\fR
.RS 4
Use the given configuration profile, instead of the default\&. If this option is specified, the string "\-\fIPROFILE\fR" will be appended to the paths of the configuration file and default key and certificate directories\&.
.sp
For example, if
\fB\-\-profile=company\fR
is used, the global configuration file will be
/etc/sslmate\-company\&.conf
and the default certificate directory will be
/etc/sslmate\-company, instead of
/etc/sslmate\&.conf
and
/etc/sslmate\&.
.sp
This option is intended for those who need to use several different SSLMate accounts on a single server, since each configuration file can contain distinct SSLMate API credentials\&.
.RE
.SH "CONFIGURATION"
.PP
Upon startup,
\fBsslmate\fR
reads configuration from the global configuration file,
/etc/sslmate\&.conf, and your personal configuration file,
~/\&.sslmate, if they exist\&. These files should contain one configuration option per line of the form
\fB\fINAME\fR\fR\fB \fR\fB\fIVALUE\fR\fR\&. Blank lines and lines starting with
#
are ignored\&. Options in your personal configuration file override options set in the global configuration file\&. The location of your personal configuration file can be changed by setting the
\fI$SSLMATE_CONFIG\fR
environment variable\&.
.PP
The following options are understood:
.PP
\fBapi_key \fR\fB\fIKEY\fR\fR
.RS 4
Your API key, which can be found on your
\m[blue]\fBonline SSLMate account page\fR\m[]\&\s-2\u[1]\d\s+2\&. This option is automatically set (in your personal configuration file) when you run
\fBsslmate link\fR\&.
.RE
.PP
\fBkey_directory \fR\fB\fIPATH\fR\fR, \fBcert_directory \fR\fB\fIPATH\fR\fR
.RS 4
The directories where
\fBsslmate\fR
places keys and certificates\&. When running as root, the default is
/etc/sslmate\&. When running as non\-root, the default is the current working directory\&.
.RE
.PP
\fBwildcard_filename \fR\fB\fIPREFIX\fR\fR
.RS 4
When creating files for wildcard certificates, use
\fIPREFIX\fR
in the filename instead of a * character\&.
.RE
.PP
\fBcert_format\&.\fR\fB\fIFORMAT\fR\fR\fB yes|no\fR
.RS 4
Enable or disable the given certificate format\&. When a format is enabled,
\fBsslmate\fR
will create a file of that format in your certificate directory when buying, reissuing, renewing, and downloading\&. After enabling a format that was previously disabled, you can create the missing files by running
\fBsslmate download \-\-all\fR\&. The formats are documented below in the CERTIFICATE FILES section\&. All formats are disabled by default except for "chained"\&.
.RE
.PP
\fBkey_type rsa|ecdsa\fR
.RS 4
The key type to use by default when buying or reissuing a certificate\&. Can be overridden by the
\fB\-\-key\-type\fR
command line flag\&. See the documentation for
\fBsslmate buy\fR
for details\&.
.RE
.PP
\fBapi_endpoint \fR\fB\fIURI\fR\fR
.RS 4
The URI to the SSLMate API endpoint\&. This option does not need to be configured under normal circumstances\&.
.RE
.SH "CONFIGURATION FILES"
.PP
~/\&.sslmate
.RS 4
Your personal configuration file\&. Options set in this file override options set in the global configuration file\&. See the "Configuration" section above for the syntax of this file\&.
.RE
.PP
/etc/sslmate\&.conf
.RS 4
The global configuration file\&. See the "Configuration" section above for the syntax of this file\&.
.RE
.PP
/etc/sslmate
.RS 4
The default directory for storing keys and certificates when run as root\&. Can be overridden by the
\fIkey_directory\fR
and
\fIcert_directory\fR
configuration options\&.
.RE
.SH "CERTIFICATE FILES"
.PP
SSLMate creates the following files for every certificate\&. The key file is placed in the configured
\fIkey_directory\fR, and the other files are placed in the configured
\fIcert_directory\fR\&. (Both directories are
/etc/sslmate
by default when running as root and
$PWD
by default when running as non\-root\&.)
.PP
\fIhostname\fR\&.key
.RS 4
The private key file for
\fIhostname\fR, in PEM encoding (specifically, the PEM encoding of the ASN\&.1 DER encoding of a PKCS#1 RSAPrivateKey (for RSA) or a RFC 3279 EcpkParameters (for ECDSA))\&. This is the default format used by OpenSSL and is accepted by typical applications on Linux\&.
.RE
.PP
\fIhostname\fR\&.crt
.RS 4
The public certificate file for
\fIhostname\fR, in PEM encoding (specifically, the PEM encoding of the ASN\&.1 DER encoding of the X\&.509 certificate)\&. This is the default format used by OpenSSL and is accepted by typical applications on Linux\&.
\fIWarning:\fR
This file does not work on its own since it does not contain the certificate chain\&. You must also configure the chain certificate(s) using one of the other formats\&.
.RE
.PP
\fIhostname\fR\&.chain\&.crt
.RS 4
The certificate chain (aka intermediate certificate) file for
\fIhostname\fR\&. This file contains the concatenation of each intermediate certificate, in PEM encoding\&. The first certificate is the issuer of the end\-entity certificate, and the last certificate is signed by the root certificate\&. The root certificate is not included\&.
.RE
.PP
SSLMate optionally creates the following files for every certificate (in the
\fIcert_directory\fR) if the indicated configuration option is set to yes\&.
.PP
\fIhostname\fR\&.chained\&.crt (cert_format\&.chained)
.RS 4
A concatenation of the certificate and chain files for
\fIhostname\fR, in PEM encoding\&. This format is enabled by default\&. This is the file you should use with most applications on Linux, which require the certificate and chain to be specified in the same file\&.
.RE
.PP
\fIhostname\fR\&.combined\&.pem (cert_format\&.combined)
.RS 4
A concatenation of the private key, certificate, and chain files for
\fIhostname\fR, in PEM encoding\&. This format is intended for Linux applications which require the key and certificates to be specified in the same file\&.
.RE
.PP
\fIhostname\fR\&.p12 (cert_format\&.p12)
.RS 4
A PKCS#12 file (also known as a P12 or PFX file) containing the private key, certificate, and chain for
\fIhostname\fR\&. The PKCS#12 file\*(Aqs password is "sslmate"\&. PKCS#12 files are primarily used by Windows applications\&.
.RE
.PP
\fIhostname\fR\&.jks (cert_format\&.jks)
.RS 4
A Java keystore file containing the private key, certificate, and chain for
\fIhostname\fR\&. The keystore\*(Aqs password is "sslmate"\&. The
\fBkeytool(1)\fR
command, from the Java runtime environment, must be installed to use this format\&. JKS files are generally used only by Java applications, such as Tomcat\&.
.RE
.PP
\fIhostname\fR\&.root\&.crt (cert_format\&.root)
.RS 4
The root certificate for
\fIhostname\fR, in PEM encoding\&. You do
\fInot\fR
generally need the root certificate, so you should leave this format disabled unless you have a special requirement\&.
.RE
.PP
\fIhostname\fR\&.chain+root\&.crt (cert_format\&.chain+root)
.RS 4
A concatenation of the chain and root certificate files for
\fIhostname\fR\&. This format is required for verifying OCSP responses and configuring OCSP stapling\&. You do not need it in a basic configuration\&.
.RE
.PP
You need to configure your server software (e\&.g\&. Apache, nginx) with the private key file (\&.key) and some combination of the \&.crt files\&. Some software (e\&.g\&. Apache) requires you to specify the certificate (\&.crt) and the chain (\&.chain\&.crt) in separate files, while other software (e\&.g\&. nginx) requires you to specify both in a single file (\&.chained\&.crt)\&.
.PP
Files which contain the private key are created with restrictive filesystem permissions (0600), and other files are created with world\-readable permissions (0644)\&. When updating a file,
\fBsslmate\fR
preserves the existing owner and permissions, including (on Linux only) ACLs\&. This lets you use filesystem permissions to grant access to applications that run as a non\-root user, and not have to worry about the permissions being disrupted when downloading an updated certificate\&.
.PP
You are encouraged to run
\fBsslmate\fR
as root, store keys and certificates in the SSLMate\-managed
\fIkey_directory\fR
and
\fIcert_directory\fR
(/etc/sslmate
by default), and to configure your server software to refer to keys and certificates in this directory\&. This makes automated renewals more seamless by ensuring that your server software always refers to the latest version of a certificate downloaded by
\fBsslmate download\fR\&.
.SH "ENVIRONMENT VARIABLES"
.PP
\fISSLMATE_CONFIG\fR
.RS 4
The path to your personal configuration file\&. Defaults to
$HOME/\&.sslmate\&.
.RE
.SH "SEE ALSO"
.PP
\m[blue]\fBOnline SSLMate Help\fR\m[]\&\s-2\u[4]\d\s+2,
\fBopenssl\fR(1)
.SH "NOTES"
.IP " 1." 4
online SSLMate account page
.RS 4
\%https://sslmate.com/account
.RE
.IP " 2." 4
online SSLMate dashboard
.RS 4
\%https://sslmate.com/dashboard
.RE
.IP " 3." 4
Mozilla's Server Side TLS Guide
.RS 4
\%https://wiki.mozilla.org/Security/Server_Side_TLS
.RE
.IP " 4." 4
Online SSLMate Help
.RS 4
\%https://sslmate.com/help
.RE
